### ISSUE TITLE
Please remove wikipedia.org out from the white-list

### ISSUE THREAD

**Issue by ghost** [R0uter/gfw_domain_whitelist#1]
This project is pretty good, but the white list seems not fully correct.
Some pages (e.g. https://zh.wikipedia.org/zh/TCP/UDP%E7%AB%AF%E5%8F%A3%E5%88%97%E8%A1%A8) of wikipedia.org was blocked by GFW.
Thanks for your great work!

**Comment by R0uter** [comment]
Im sorry about that,it was my spider's glitch. I was not fully tested..... I will fix this problems in next couple days.
