### ISSUE TITLE
googlexxx need to be removed also

### ISSUE THREAD

**Issue by ghost** [R0uter/gfw_domain_whitelist#2]
Seems these four domains also need to be removed:
"googleadservices.com":1,
"googleapis.com":1,
"googlesyndication.com":1,
"googletagmanager.com":1,

**Comment by R0uter** [comment]
Im sorry about that, I updated my spider and deleted all database. Now this little spidy is working hardly to gather all china mainland domian.  --yes, other domian will no longer listed in this whitelist.   And now I will roll back this 2000+ domian for good. XD

**Comment by R0uter** [comment]
all updated!
