### ISSUE TITLE
Readme中有几处balance拼写错了

### ISSUE THREAD

**Issue by CometYZ** [R0uter/gfw_domain_whitelist#25]
Firefox  
whitelist.pac 50ms 
load **balabce**: whitelist.pac 40ms

Chrome  
whitelist.pac 70ms
load **balabce**: whitelist.pac 68ms

Safari  
whitelist.pac 50ms  
load **balabce**: whitelist.pac 44ms

**Comment by R0uter** [comment]
感谢提醒，已经好多年前的了，我把readme整体修了一波，希望这个repo还能有用。

**Comment by CometYZ** [comment]
这个pac已经用了几个月了，在mac上配合v2rayu运行良好，网上能找到的其他pac都不适配safari。我自己用https://github.com/pexcn/daily 的规则覆盖了这个pac的规则，其他配置都没有改
