### ISSUE TITLE
Thank you so much!

### ISSUE THREAD

**Issue by catshitz** [R0uter/gfw_domain_whitelist#3]
支持白名单 感谢常更新！

**Comment by catshitzhou** [comment]
更新啦！一点新的建议：期待出一个能在SwitchyOmega中使用的，如同gfwlist.txt一样的autoproxy名单，这样可以更方便地对不同网站进行灵活的调整，也可以减少名单的更新频率，甚至可以让大家一起来帮忙对名单做贡献，谢谢！

**Comment by R0uter** [comment]
暂时没有时间和精力，我自己用 Safari 所以也不能用这个插件😂，等过段时间我试试看。

**Comment by catshitzhou** [comment]
反馈：使用 shadowsocks 3.3.6 ，白名单 whitelist.pac 作为本地PAC代理，网络环境与之前相同，代理节点及服务器正常未变，近几次更新（大约自12月以来），经常出现使用chrome浏览器（Tampermonkey无异常脚本，扩展仅uBlockOrigin常见规则及Adfree，亦与以前相同未变）浏览部分国外网盘、图床、博客及论坛类网站打开速度极为缓慢甚至持续空白（网盘类如mega、google云盘、mixtape、dropbox等，图床类如imgur、gfycat、hostingpics等，博客论坛类如blogspot等），需切换全局代理才能恢复正常，请问是什么原因，怎样恢复正常？谢谢！

**Comment by R0uter** [comment]
已经更新，你试试看

**Comment by catshitz** [comment]
经初步测试，大多数网站已恢复正常，非常感谢！另新发现网盘mediafire仍有延迟加载或长时间空白，切换全局代理恢复正常。

**Comment by catshitz** [comment]
经初步测试，多数提及网站恢复正常，但仍然都偶有加载缓慢与卡白屏现象，又有如mediafire网盘与部分国外论坛更甚，不知具体原因为何，另补充hosts文件未改。麻烦您了，谢谢！
