### ISSUE TITLE
走IP时，重定向了

### ISSUE THREAD

**Issue by skiy** [R0uter/gfw_domain_whitelist#4]
走阿里云的 IP时，被重定向了。难道说不可以打开IP的网站？ 

120.24.152.200

**Comment by R0uter** [comment]
确实有问题，我改改。现在再试试看。

**Comment by skiy** [comment]
有些网站还是有问题。比如 360搜索里的样式href：http://s7.qhres.com/static/f56fc8284957c595/common/login.css

**Comment by R0uter** [comment]
这个问题是由于 qhres.com 并未被白名单收录所以走了代理。 这样的话你可以自行动手在白名单里按照格式添加一行。
