### ISSUE TITLE
[Bug report] 生成的 pac 文件中的内容有误

### ISSUE THREAD

**Issue by foobarjohnny** [R0uter/gfw_domain_whitelist#6]
1. 生成 pac 文件时, 对 "cn" 结尾的处理有误, 例如下面这样

server=/ffdy.cn.com/114.114.114.114                       被处理成                    "ffdy.cn":1,
server=/hdn.xnimg.cn.cdngc.net/114.114.114.114		被处理成		"hdn.xnimg":1,
server=/sekong.cn.com/114.114.114.114			被处理成			"sekong.cn":1,
server=/www.givaudan.cn.gccdn.net/114.114.114.114	被处理成		"www.givaudan":1,

2. 生成 pac 文件时, 另外一个处理有误的地方

server=/www.dell-brand.com/114.114.114.114		被处理成			"www.dell":1,
server=/www.dell.com/114.114.114.114				被处理成		"www.dell":1,

**Comment by R0uter** [comment]
all fixed!
