### ISSUE TITLE
建议添加一个通过ip判断是否走代理白名单pac文件

### ISSUE THREAD

**Issue by fanck0605** [R0uter/gfw_domain_whitelist#8]
domain 列表毕竟只是民间收集不够精确，单纯采用 domain 判断的话有可能误判，apnic 有的精确的[国内 IP 列表](https://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-latest)（包括 IPv6），仅需解决某些污染问题就可以最大限度的保证分流准确。
思路：
污染问题一般只发生在 xxxlist，该列表域名走 proxy，其余 dnsResolve 后 IP 分流

**Comment by R0uter** [comment]
我之所以做了一个根据域名来分流的列表，就是为了避免DNS解析，如果不请求DNS，就可以从根本上避免这个问题。你说的用gfwlist，我说过这个问题，gfwlist变动太频繁了（主要是认证的网站每天都在增加）， 用白名单能很好的避免这个问题，就算一个白名单旧了，也能正常使用。（（（我觉得我们可以深入讨论下0.0

**Comment by uragasit** [comment]
我觉得这个提议蛮好的，我们买的代理流量一般是有一个额度的，特别是有一些中文的在线电影网站可能服务器设在国外，如果不小心看了高清电影那就惨了，当然我是小白，不知道技术上如何实施。

**Comment by R0uter** [comment]
如同破娃讲的，使用版名单需要你有一个大流量或者不限流量的代理，如果没有，就还是使用黑名单更好一些。

**Comment by al123xiaaaa** [comment]
看了下最新版的pac好像是加上了ip判断？

**Comment by al123xiaaaa** [comment]
> 我之所以做了一个根据域名来分流的列表，就是为了避免DNS解析，如果不请求DNS，就可以从根本上避免这个问题。你说的用gfwlist，我说过这个问题，gfwlist变动太频繁了（主要是认证的网站每天都在增加）， 用白名单能很好的避免这个问题，就算一个白名单旧了，也能正常使用。（（（我觉得我们可以深入讨论下0.0

@fanck0605 的意思是把那些直接走国内ip的请求像内网ip一样做成直接走本地，和DNS没有关系。因为有很多国内视频网站的视频的确是直接用ip来获取的。不过不知道加上那么多国内ip后的pac文件性能会怎样。

**Comment by R0uter** [comment]
用ip？pac是给浏览器用的，理论上直接请求ip是不走pac策略的啊。

**Comment by fanck0605** [comment]
使用ip分流，ip列表用简单的hash算法存储。也正是因为简单，hash表的长度很诡异，很有必要优化一下。
https://github.com/fanck0605/gfw_whitelist/blob/gh-pages/chnroute.pac
travis-ci每日更新
